name: stpgcn
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.7.9
  - pytorch=1.9.0=py3.7_cuda102_cudnn8_0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - mne==0.22.1
  - nibabel==3.2.1
  - nilearn==0.8.0
